"""rename department

Revision ID: 315c0e1d1c5f
Revises: bdb5629b67f2
Create Date: 2024-07-02 16:10:56.191695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315c0e1d1c5f'
down_revision = 'bdb5629b67f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###